config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'sessions/new'
  get 'sessions/index'
  get 'sessions/create'
  get 'sessions/destroy'
  patch 'user/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :todos
  resources :sessions, only: [:create, :destroy]
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  has_secure_password

  validates :email, presence: true,
  format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
  message: "is not valid"},
  uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6}, :on => create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
      !current_user.nil?
  end
  def authorized
     redirect_to root_url unless logged_in?
  end
  def show_user_page
    if logged_in?
        redirect_to "/todos"
    end
  end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to '/todos', notice: "Logged in!"
    else
      flash.now[:alert] ="Email or Password is incorrect"
      render "welcome/index"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authorized
  before_action :fetch_todo, only: [:destroy, :edit, :update, :index]
  before_action :all_todos, only: [:index, :edit]

  def index
    @todo = Todo.new
  end

  def new
  end

  def edit
    render 'index'
  end

  def create
    @todo = current_user.todos.create(permit_todo)

    if @todo.save
      redirect_to '/todos'
    else
      puts @todo.errors.messages
    end
  end

  def update
    if @todo.update(permit_todo)
      redirect_to '/todos'
    end
  end

  def destroy
    @todo.destroy
    redirect_to '/todos'
  end

  private

  def permit_todo
    params.require(:todo).permit(:todo)
  end
  def fetch_todo
    if params.has_key?(:id)
      @todo = Todo.find(params[:id])
    end
  end
  def all_todos
    @todos = current_user.todos
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(permit_user)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/todos'
    else
      puts @user.errors.messages
      render 'welcome/index'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id]);

    if @user.update(permit_user)
      redirect_to '/todos'
    else
      render 'edit'
    end
  end

  private

  def permit_user
    params.require(:user).permit(:email, :password, :password_confirmation, :user_name, :image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :show_user_page

  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeroesTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<div id="todo-page-container">
  <div id="header-section-container">
    <div class="header-section">
      <%= form_for @todo do |form| %>
        <div class="title-container">
          <div class="form-input-container">
            <p class="form-title"> HEROS <span class="form-title-b">TODO</p>
            <%= submit_tag("ADD") %>
            <%= form.text_field :todo %>
          </div>
          <div class="profile-image-container" id="profile-image-container">
            <img src="https://res.cloudinary.com/xrole/image/upload/v1577661794/BlueFlameIndoors/heroUser.jpg">
              <div class="control-container" id="control-container">
                <p> <%= link_to 'profile', 'users/id/edit', method: 'get', class: 'link-style space-up space-down' %> <p />
                <%= link_to "Logout", 'sessions/destroy', method: 'delete', class: "link-style space-up" %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="todo-list-section">
    <div class="date-section">
     <p> MONDAY </p>
     <div>
      <p>Date:</p>
     </div>
    </div>
    <di>
      <% @todos.each do |todo| %>
        <div class="todo-container">
          <div class="todo-container-inner">
            <p> <input type="checkbox" id= <%= todo.id %> name="vehicle" value="Bike"> <span class="todo"> <%= todo.todo %> </span> </p>
          </div>
          <div class="todo-container-actions">
            <div class="edit">
              <%= link_to "Edit", edit_todo_path(todo), class: 'link-style' %>
            </div>
            <div class="delete">
              <%= link_to "Delete", todo_path(todo), method: 'delete', class: 'link-style' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div id="todo-page-container">
  <div id="header-section-container">
    <div class="header-section">
      <%= form_with scope: :todo, local: true do |form| %>
        <div class="title-container">
          <div class="form-input-container">
            <p class="form-title"> HEROS <span class="form-title-b">TODO</p>
            <%= submit_tag("ADD") %>
            <%= form.text_field :title %>
          </div>
          <div class="profile-image-container">
            <img src="https://res.cloudinary.com/xrole/image/upload/v1577661794/BlueFlameIndoors/heroUser.jpg">
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="todo-list-section">
    <div class="date-section">
     <p> MONDAY </p>
     <div>
      <p>Date:</p>
     </div>
    </div>
    <%= form_with scope: :todo, local: true do |form| %>
      <div class="todo-container">
        <div class="todo-container-inner">
          <p> Checkbox <span class="todo"> Leveling up on Docker </span> </p>
          </div>
        <div class="todo-container-actions">
          <div class="edit"> <p>Edit</p></div>
          <div class="delete"><p>Delete</p></div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="welcome-page-container">
  <div class="background-container" >
    <h1> HEROES TODO </h1>
    <p id=”alert” class="danger"><%= alert %></p>
    <div class="auth-container">
      <p class="register" id="register"> Register </p>
      <p class="login" id="login"> Login </p>
    </div>
    <div class="auth-form">
      <div id="register_form">
      <%= form_with scope: :user, url: users_path, local: true do |form| %>
        <% if @user && @user.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li class="error_list"><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-title-container"> <h3> REGISTER </h3></div>
        <div class="form-field">
          <%= form.label :Email %>
          <%= form.email_field(:email) %>
        </div>
        <div class="form-field">
          <%= form.label :Password %>
          <%= form.password_field(:password) %>
        </div>
        <div class="form-field">
          <%= form.label :ConfirmPassword %>
          <%= form.password_field(:password_confirmation) %>
        </div>
        <p class="submit">
          <%= submit_tag("Register") %>
        </p>
      <% end %>
      </div>
      <div id="login_form">
        <%= form_with scope: :user, url: sessions_create_path, method: "get", local: true do |form| %>
          <% if @user && @user.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li class="error_list"><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-title-container"> <h3> LOGIN </h3></div>
          <div class="form-field">
            <%= form.label :Email %>
            <%= form.email_field :email, :id => "login_email" %>
          </div>
          <div class="form-field">
            <%= form.label :Password %>
            <%= form.password_field :password, :id => "login_pass" %>
          </div>
          <p class="submit">
            <%= submit_tag("Register") %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>